//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DHDoiSim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DMQHPX
    {
        public int ID { get; set; }
        public string Ten_QH { get; set; }
        public string Ten_PX { get; set; }
        public Nullable<int> ID_Phong { get; set; }
        public string TenPhong { get; set; }
        public string TTVT { get; set; }
    }
}
