//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DHDoiSim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DMTo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DMTo()
        {
            this.Sim_Trang = new HashSet<Sim_Trang>();
            this.UserLists = new HashSet<UserList>();
            this.Sim_Phieu = new HashSet<Sim_Phieu>();
            this.DMNhomDiaBans = new HashSet<DMNhomDiaBan>();
        }
    
        public int ID { get; set; }
        public Nullable<int> ID_Phong { get; set; }
        public string TenDonVi { get; set; }
        public string TenTat { get; set; }
    
        public virtual DMPhong DMPhong { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sim_Trang> Sim_Trang { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserList> UserLists { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sim_Phieu> Sim_Phieu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DMNhomDiaBan> DMNhomDiaBans { get; set; }
    }
}
