//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DHDoiSim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoiSim_DM_ImageUnit
    {
        public int ID { get; set; }
        public string MaUnit { get; set; }
        public string LoaiImage { get; set; }
        public string TenLoaiImage { get; set; }
        public string HuongDan { get; set; }
        public string GhiChu { get; set; }
        public string Show { get; set; }
    }
}
