//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DHDoiSim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sim_Phieu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sim_Phieu()
        {
            this.Sim_Phieu_NhatKyUpdate = new HashSet<Sim_Phieu_NhatKyUpdate>();
        }
    
        public int ID { get; set; }
        public Nullable<int> ID_Sim_KH { get; set; }
        public Nullable<int> ID_Sim_Trang { get; set; }
        public string SoDT { get; set; }
        public string LoaiTB { get; set; }
        public string LoaiDienThoai { get; set; }
        public string ModelDienThoai { get; set; }
        public string Ten_QH { get; set; }
        public string Ten_PX { get; set; }
        public string DiaChiHenDoiSim { get; set; }
        public Nullable<System.DateTime> GioHen { get; set; }
        public Nullable<int> ID_MucUuTien { get; set; }
        public Nullable<int> ID_Phong { get; set; }
        public Nullable<int> ID_To { get; set; }
        public Nullable<System.DateTime> TimeXP { get; set; }
        public string UserXP { get; set; }
        public string NoiDungXP { get; set; }
        public Nullable<System.DateTime> TimeChiaPhieu { get; set; }
        public string UserChiaPhieu { get; set; }
        public string NoiDungChiaPhieu { get; set; }
        public Nullable<System.DateTime> TimeNhanPhieu { get; set; }
        public string UserNhanPhieu { get; set; }
        public string NoiDungNhanPhieu { get; set; }
        public Nullable<System.DateTime> TimeCapNhatKetQuaThucHien { get; set; }
        public string UserThucHien { get; set; }
        public Nullable<System.DateTime> DateThucHien { get; set; }
        public string NoiDungThucHien { get; set; }
        public Nullable<int> ID_KetQuaThucHien { get; set; }
        public string Image_CMT_Truoc { get; set; }
        public string Image_CMT_Sau { get; set; }
        public string Image_BienBan { get; set; }
        public string SerialNumber { get; set; }
        public string GhiChu { get; set; }
        public Nullable<int> ID_DonViKT { get; set; }
        public string PhanMemKhoaPhieu { get; set; }
        public Nullable<System.DateTime> TimeChiaPhieu2 { get; set; }
        public string UserChiaPhieu2 { get; set; }
        public string NoiDungChiaPhieu2 { get; set; }
        public Nullable<System.DateTime> TimeKhoaPhieu { get; set; }
        public string UserKhoaPhieu { get; set; }
        public string NoiDungKhoaPhieu { get; set; }
        public string Image_CamKetKhongCC { get; set; }
        public Nullable<int> ID_LyDoTon { get; set; }
        public Nullable<System.DateTime> TimeNhapTon { get; set; }
        public string UserNhapTon { get; set; }
        public string NoiDungNhapTon { get; set; }
        public Nullable<int> ID_LoaiGiayTo { get; set; }
        public string GhiChu11 { get; set; }
        public Nullable<System.DateTime> NgayHenMoi { get; set; }
        public string CCCD_KhachHang { get; set; }
    
        public virtual DMKetQuaThucHien DMKetQuaThucHien { get; set; }
        public virtual DMLoaiGiayTo DMLoaiGiayTo { get; set; }
        public virtual DMLyDoTon DMLyDoTon { get; set; }
        public virtual DMMucUuTien DMMucUuTien { get; set; }
        public virtual DMPhong DMPhong { get; set; }
        public virtual DMTo DMTo { get; set; }
        public virtual Sim_KH Sim_KH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sim_Phieu_NhatKyUpdate> Sim_Phieu_NhatKyUpdate { get; set; }
    }
}
