//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DHDoiSim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sim_KH_NhatKyUpdate
    {
        public int ID { get; set; }
        public Nullable<int> ID_Sim_KH { get; set; }
        public string SoDT { get; set; }
        public Nullable<int> ID_StatusOBKH { get; set; }
        public string NguoiGoi { get; set; }
        public Nullable<System.DateTime> GioGoi { get; set; }
        public Nullable<System.DateTime> GioHen { get; set; }
        public string QHHenDoiSim { get; set; }
        public string PXHenDoiSim { get; set; }
        public string DiaChiHenDoiSim { get; set; }
        public string GhiChu { get; set; }
        public string TenPhong { get; set; }
    
        public virtual DMStatusOBKH DMStatusOBKH { get; set; }
        public virtual Sim_KH Sim_KH { get; set; }
    }
}
