//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DHDoiSim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sim_Trang
    {
        public int ID { get; set; }
        public Nullable<int> STT { get; set; }
        public string LoaiHang { get; set; }
        public Nullable<double> MenhGia { get; set; }
        public Nullable<int> ThucCap { get; set; }
        public Nullable<double> ThanhTien { get; set; }
        public string SerialNumber { get; set; }
        public string BaoHanh { get; set; }
        public Nullable<System.DateTime> NgayBanGiao { get; set; }
        public string GhiChu { get; set; }
        public Nullable<int> ID_Phong { get; set; }
        public Nullable<int> ID_To { get; set; }
        public Nullable<System.DateTime> TimeUpdate { get; set; }
        public string UserUpdate { get; set; }
        public Nullable<System.DateTime> Timestamps { get; set; }
        public Nullable<int> ID_StatusSuDung { get; set; }
        public Nullable<int> ID_DonViKT { get; set; }
    
        public virtual DMDonViKT DMDonViKT { get; set; }
        public virtual DMPhong DMPhong { get; set; }
        public virtual DMStatusSuDung DMStatusSuDung { get; set; }
        public virtual DMTo DMTo { get; set; }
    }
}
