//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DHDoiSim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sim_KH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sim_KH()
        {
            this.Sim_Phieu = new HashSet<Sim_Phieu>();
            this.Sim_KH_NhatKyUpdate = new HashSet<Sim_KH_NhatKyUpdate>();
        }
    
        public int ID { get; set; }
        public string SoDT { get; set; }
        public string Loai_TB { get; set; }
        public string BTS_Name { get; set; }
        public string Code { get; set; }
        public string Model { get; set; }
        public string Dia_Chi_BTS { get; set; }
        public string Don_Vi { get; set; }
        public string TTVT { get; set; }
        public string Dia_Chi_BTS2 { get; set; }
        public Nullable<int> Phuong_Xa_ID { get; set; }
        public Nullable<int> Quan_Huyen_ID { get; set; }
        public Nullable<int> Ve_Tinh_ID { get; set; }
        public string TenPhong { get; set; }
        public string Ten_TT { get; set; }
        public string Ten_QH { get; set; }
        public string Ten_PX { get; set; }
        public Nullable<int> Doi_ID { get; set; }
        public string Ten_Doi { get; set; }
        public Nullable<int> TT_ID { get; set; }
        public Nullable<System.DateTime> TimeUpFile { get; set; }
        public string UserUpFile { get; set; }
        public Nullable<System.DateTime> Timestamps { get; set; }
        public Nullable<int> ID_DonViKT { get; set; }
        public Nullable<int> ID_StatusOBKH { get; set; }
        public string NguoiGoi { get; set; }
        public Nullable<System.DateTime> GioGoi { get; set; }
        public Nullable<System.DateTime> GioHen { get; set; }
        public string DiaChiHenDoiSim { get; set; }
        public string GhiChu { get; set; }
        public Nullable<int> ID_KetQuaThucHien { get; set; }
        public string LyDoPhanDiaBan { get; set; }
        public string TieuChi { get; set; }
        public string GhiChu1 { get; set; }
        public string GhiChu2 { get; set; }
        public string GhiChu3 { get; set; }
        public string QHHenDoiSim { get; set; }
        public string PXHenDoiSim { get; set; }
        public string TenPhanMemNhap { get; set; }
        public string DiaBanHenDoiSim { get; set; }
        public Nullable<int> isSendSMS { get; set; }
    
        public virtual DMDonViKT DMDonViKT { get; set; }
        public virtual DMKetQuaThucHien DMKetQuaThucHien { get; set; }
        public virtual DMStatusOBKH DMStatusOBKH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sim_Phieu> Sim_Phieu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sim_KH_NhatKyUpdate> Sim_KH_NhatKyUpdate { get; set; }
    }
}
