//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DHDoiSim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sim_Phieu_NhatKyUpdate
    {
        public int ID { get; set; }
        public Nullable<int> ID_Sim_Phieu { get; set; }
        public string SoDT { get; set; }
        public Nullable<System.DateTime> TimeUpdate { get; set; }
        public string UserUpdate { get; set; }
        public string NoiDungUpDate { get; set; }
    
        public virtual Sim_Phieu Sim_Phieu { get; set; }
    }
}
