//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DHDoiSim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThongKeNSCL
    {
        public int ID { get; set; }
        public Nullable<int> Thang { get; set; }
        public Nullable<int> Nam { get; set; }
        public Nullable<int> ID_Ky { get; set; }
        public string MaDonVi { get; set; }
        public string UserName { get; set; }
        public string HoTen { get; set; }
        public string Ten { get; set; }
        public string ChucDanh { get; set; }
        public Nullable<int> GoiHenDoiSim4G_ThanhCong { get; set; }
        public Nullable<int> GoiHenDoiSim4G_KHDaDoiTaiQuay { get; set; }
        public Nullable<int> ThucHienDoiSim4G_ThanhCong { get; set; }
        public Nullable<int> GoiHenDoiSim4G_XuatPhieuDoiSim { get; set; }
        public Nullable<double> TongDiem { get; set; }
    }
}
