//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DHDoiSim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThongKeDoiSimThanhCong
    {
        public int ID { get; set; }
        public Nullable<int> ID_Phong { get; set; }
        public string SoDT { get; set; }
        public string UserDoiSim { get; set; }
        public string HoTenUserDoiSim { get; set; }
        public Nullable<System.DateTime> NgayDoiSim { get; set; }
        public string NgayDoiSim_VN { get; set; }
    }
}
