//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DHDoiSim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThongKeOutBound
    {
        public int ID { get; set; }
        public string UserName { get; set; }
        public string HoTen { get; set; }
        public string Ten { get; set; }
        public string MaDonVi { get; set; }
        public string TenDonVi { get; set; }
        public Nullable<System.DateTime> TuNgay { get; set; }
        public Nullable<System.DateTime> DenNgay { get; set; }
        public Nullable<int> PhieuDaXuat { get; set; }
    }
}
