//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DHDoiSim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThongKe
    {
        public int ID { get; set; }
        public Nullable<int> ID_Phong { get; set; }
        public Nullable<int> DoiSimThanhCong { get; set; }
        public Nullable<int> SoSimTrangDaCap { get; set; }
        public Nullable<int> DoiSimKhongThanhCong { get; set; }
        public Nullable<int> ChuaCoKetQua { get; set; }
        public Nullable<int> TongSoPhieu { get; set; }
        public Nullable<double> TyLeDoiSimThanhCong { get; set; }
        public Nullable<System.DateTime> NgayBC { get; set; }
        public Nullable<System.DateTime> NgayGioTaoBaoCao { get; set; }
        public string TenPhong { get; set; }
        public Nullable<int> TongPhieuTinhLyLe { get; set; }
        public Nullable<int> SoSimDoiNgoaiDanhSach { get; set; }
    
        public virtual DMPhong DMPhong { get; set; }
    }
}
