//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DHDoiSim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThongKeOutBound
    {
        public int ID { get; set; }
        public string UserName { get; set; }
        public string HoTen { get; set; }
        public string Ten { get; set; }
        public string MaDonVi { get; set; }
        public string TenDonVi { get; set; }
        public Nullable<System.DateTime> TuNgay { get; set; }
        public Nullable<System.DateTime> DenNgay { get; set; }
        public Nullable<int> PhieuDaXuat { get; set; }
        public Nullable<int> TongCuocGoi { get; set; }
        public Nullable<int> ThanhCong { get; set; }
        public Nullable<int> KhongThanhCong { get; set; }
        public Nullable<int> DaDoi { get; set; }
        public Nullable<int> DangGoi { get; set; }
        public Nullable<int> KHDongYDS { get; set; }
        public Nullable<int> KHKhongDYDS { get; set; }
        public Nullable<int> DaGoiChuaCoKQ { get; set; }
        public Nullable<int> KhongLLDuoc { get; set; }
        public Nullable<int> KHTuDS { get; set; }
        public Nullable<int> KHChuyenTinh { get; set; }
        public Nullable<int> KHDaDS { get; set; }
        public Nullable<int> PVT { get; set; }
        public Nullable<int> PHT { get; set; }
        public Nullable<int> PKT { get; set; }
        public Nullable<int> PKTHT { get; set; }
        public Nullable<int> PVIP { get; set; }
        public Nullable<int> PTH { get; set; }
    }
}
