//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DHDoiSim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThongKeChiTietDonVi
    {
        public Nullable<int> SoLuongOKRThang { get; set; }
        public Nullable<int> SoPhieuTiepNhan { get; set; }
        public Nullable<int> SoPhieuDoiThanhCong { get; set; }
        public Nullable<double> TyLeDoiThanhCong { get; set; }
        public Nullable<int> PhieuNhanTrongNgay { get; set; }
        public Nullable<int> PhieuDoiThanhCongTrongNgay { get; set; }
        public Nullable<double> TyLeThanhCongTrongNgay { get; set; }
        public Nullable<int> TongSoPhieuTon { get; set; }
        public Nullable<int> PhieuTonQua2Ngay { get; set; }
        public Nullable<int> DiemOKRThang { get; set; }
        public string GhiChu { get; set; }
        public string TenTo { get; set; }
        public Nullable<int> IDTo { get; set; }
        public int ID { get; set; }
        public Nullable<int> DoiSimThanhCong { get; set; }
        public Nullable<int> DoiSimKhongThanhCong { get; set; }
        public Nullable<int> ChuaCoKetQua { get; set; }
        public Nullable<int> TongSoPhieu { get; set; }
        public Nullable<double> TyLeDoiSimThanhCong { get; set; }
    }
}
