//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DHDoiSim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserList
    {
        public int ID_User { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public string Avatar { get; set; }
        public string Name { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string Phone { get; set; }
        public Nullable<int> ID_Permission { get; set; }
        public Nullable<System.DateTime> Last_Login { get; set; }
        public string Last_Seen { get; set; }
        public string Last_Seen_URL { get; set; }
        public Nullable<int> ID_Phong { get; set; }
        public Nullable<int> ID_To { get; set; }
        public Nullable<System.DateTime> Timestamps { get; set; }
        public Nullable<bool> HoatDong { get; set; }
        public string UserCreate { get; set; }
        public string MaDonVi { get; set; }
        public string GhiChu { get; set; }
    
        public virtual DMPhong DMPhong { get; set; }
        public virtual DMTo DMTo { get; set; }
        public virtual Permission Permission { get; set; }
    }
}
